### ISSUE TITLE
after dom change the waypoint is not working even $.waypoints('refresh') not do the work

### ISSUE THREAD

**Issue by xainpro** [imakewebthings/waypoints#177]
http://jsfiddle.net/VxqNa/9/
please check this issue...

**Comment by kricore** [comment]
Thank you for this excellent plugin.
Sorry to bump this old thread, but the code in your earlier comment ( http://jsfiddle.net/VxqNa/11/ - I know it is really old) it is not working for 4.0.0.

Is this possible with the 4.0 version (I am not using the infinite loop plugin)?

**Comment by imakewebthings** [comment]
@kricore I'm not 100% clear what you're asking. You're curious about which part of that fiddle and whether it can be done in 4.0? (Though no matter what, the answer is "yes." Waypoints hasn't lost capability since then, though the API has changed.)

**Comment by kricore** [comment]
I 'm sorry, I wasn't clear. I need waypoints in newly created DOM elements as well. 

The code in the previous fiddle produces errors. Call be dumb, and you might be correct, but I cannot seem to find a reference for this in the documentation.

**Comment by imakewebthings** [comment]
@xainpro You are not dumb. There isn't anything in the documentation on how to create waypoints on elements added dynamically because there is no one way to add elements. It always depends on what you're doing and how you're doing it.

http://jsfiddle.net/imakewebthings/VxqNa/27/

That is the previous fiddle updated to use 4.0. I hope it's a useful example. The only change I had to make to get it working again was change `this`, which used to refer to the element, to `this.element` (see http://imakewebthings.com/waypoints/api/waypoint/#element-property).

**Comment by kricore** [comment]
Thank you Caleb and sorry for the pestering, but the fiddle is using the 3.1.1 version.
Btw, the https://rawgit.com/imakewebthings/waypoints/4.0.0/lib/jquery.waypoints.js URL resolves to a 3.1.1 file.
With the 4.0 I keep getting: "$items.waypoint is not a function"

**Comment by imakewebthings** [comment]
Ah, I did use the wrong link. http://jsfiddle.net/imakewebthings/VxqNa/28/ is using the master branch, which is 4.0.0. It still works. Can you show me your error happening on a fiddle or a link?

**Comment by kricore** [comment]
Thank for all the help, I got it fixed in the end. I was using two waypoints and one was firing ( a trigger() function ) like crazy. Removed that instance, switched to your code and all is good now.

Keep up the good work Caleb :)
