### ISSUE TITLE
Enable / Disable functions undefined?

### ISSUE THREAD

**Issue by samhibberd** [imakewebthings/waypoints#363]
Hi, great plugin!

Im having some issues getting the enable/disable functions to work, even this simple call (based on the  example in the docs) is retuning a function undefined:

```
	var searchToolsWaypoint = $('#search-form').waypoint({
		handler: function(direction) {
			var holder = $('#results');
			if(direction == 'up')
			{
				holder.removeClass('fixed-searchtools');
			}
			else
			{
				holder.addClass('fixed-searchtools');
			}
		},
		offset: $('body').hasClass('logged-in') ? $('#sub-header').innerHeight() : 0
	});

	Far.add(Far.waypoints, { key: 'searchTools', value: searchToolsWaypoint });

	searchToolsWaypoint.disable();
```
Any ideas what i'm doing wrong?

**Comment by imakewebthings** [comment]
From the [Waypoint class doc page](http://imakewebthings.com/waypoints/api/waypoint):

```js
var waypoints = $('#options-only').waypoint({
  handler: function(direction) {
    notify(this.element.id + ' hit')
  }
})
```

> In the example above, waypoints will be an array of Waypoint instances, one for each of the elements matching the selector.

Your `searchToolsWaypoint` is an array, you need to call `disable` on each of the elements of the array, not `searchToolsWaypoint` itself. The `$.fn.waypoint` version the constructor always returns an array since `$(selector)` could return any number of elements. You could loop, but since you're just creating one waypoint you can index into the array.

```js
searchToolsWaypoint[0].disable();
```
