### ISSUE TITLE
With intercalated elements doesn't work

### ISSUE THREAD

**Issue by joseluisq** [imakewebthings/waypoints#373]
Note in this code appears a `.panel` element below each section:

```html
<section id="section-1" class="section">
  <div>
    <a href="#" class="btnplus" data-panel-id="panel-1">Open the panel</a>
  </div>
</section>

<div id="panel-1" class="section panel"></div>

<section id="section-2" class="section">
  <div>
    <a href="#" class="btnplus" data-panel-id="panel-2">Open the panel</a>
  </div>
</section>

<div id="panel-2" class="section panel"></div>
```

```js
$('section').waypoint(function(direction) {
  var $active = $(this);

  if (direction === 'up') {
    $active = $active.prev();
  }

  if (!$active.length) {
    $active = $(this);
  }

  console.log($active.attr('id'));
  // Output is: "undefined"
}, {
  offset: '25%'
});
```

Exists some solution for this?
Regards.

**Comment by imakewebthings** [comment]
I'd just like to say I had never seen or heard the word "intercalated" until now, but it's a terrific word. Thank you.

This ticket is a great example of something that shouldn't be opened here in the bug tracker but should instead be asked on Stack Overflow. From the [Contributing Guidelines](https://github.com/imakewebthings/waypoints/blob/master/CONTRIBUTING.md):

> The GitHub issue tracker is exclusively for opening demonstrable bugs with the library or for discussing/implementing enhancements. If you need general help with Waypoints try searching through existing closed tickets, searching through the [#jquery-waypoints](http://stackoverflow.com/questions/tagged/jquery-waypoints) tag on StackOverflow, or asking your question there using that tag. If you do ask a question on StackOverflow, please follow the guidelines for [asking a good question](http://stackoverflow.com/help/how-to-ask).

Now, it seems to me like you copied this chunk of code from an old tutorial somewhere, or the old version of the project page. The big change in Waypoints 3 that matters here is `this` is no longer the element, it's the instance of the Waypoint class. To get at the element, you must reference `this.element`. Also, you may have better luck using Waypoint's [previous](http://imakewebthings.com/waypoints/api/previous/) and [next](http://imakewebthings.com/waypoints/api/next/) methods instead of jQuery's DOM dependent `prev` to work around those *intercalated* panel elements.

**Comment by joseluisq** [comment]
I understand it, so I guess I should ask at Stack Overflow.
Thanks anyway.
