### ISSUE TITLE
.next() not working if page is initially scrolled

### ISSUE THREAD

**Issue by trurl-master** [imakewebthings/waypoints#375]
I'm not sure is it normal behaviour or an issue, but consider http://imakewebthings.com/waypoints/api/next/
If you scroll the page down and then reload it (so that you have some initial scroll on page load) then .next() is not triggered (only green and red boxes are there).
It can easily be avoided by using setTimeout, but still i wondered is it by design?

Thank you for great plugin!

**Comment by imakewebthings** [comment]
I'm aware of this, and if the only options are "by-design" or "bug" I'll choose by-design but it's more of a side effect of the facts. The fact being: Waypoints are created one after another and run their initial checks immediately. There is no next because the next waypoint hasn't been created at that point. Hence why `setTimeout` will make it work, because that delays the trigger until after all waypoints have been created.

Some options for smoothing this over have crossed my mind, such as a batch creation method that waits to check until the whole batch has been created. Everything I've come up with has struck me as too much API complication for little gain given how minor `next` is in the scheme of things. I'll keep my brain working on it in the background, though. If you or anyone else has an elegant solution please shout it out.

**Comment by imakewebthings** [comment]
Reopening, as the proposed solution for #384 should also fix this.

**Comment by imakewebthings** [comment]
The fix for #384 did also fix this. That is now released in 4.0.0.
