### ISSUE TITLE
Event not firing

### ISSUE THREAD

**Issue by henlnhl** [imakewebthings/waypoints#382]
I have tried to include waypoints into my Struts 2 web application. The purpose was to grab a scroll event and hide/show a couple different elements.  For some reason the event is not being captured when I scroll.  The event will capture after a page resize but not before.  Here is the code in question, the first console message shows that Im in the ready function but the second does not show upon scrolling.  Is this a bug?  

```js
$(document).ready(function(){
  var tabContainerHeight = $('.tabContainer').outerHeight(true);
  var origTblWidth;
  console.log('inside ready func');
  $('#origTbl').waypoint({
    handler: function(event, direction) {
      if(direction === "down"){
         origTblWidth = $('#origTbl').width();
         $('#tHeader').addClass('sticky');
         $('#tHeader').width(origTblWidth);
         $('.sticky').css('top', tabContainerHeight);
         $('#tHeader').removeClass('elHide');
      }else{
         $('#tHeader').addClass('elHide');
         $('#origTbl tr:first-child').removeClass('sticky');
      }
      console.log('waypoint reached');
    }
  });

  $(window).on('resize', function(){
    origTblWidth = $('#origTbl').width();
    $('#tHeader').width(origTblWidth);
  });
});
```

**Comment by imakewebthings** [comment]
Handlers in waypoints haven't been passed the `event` parameter since 1.x. I'm sorry to say you've run into an old an poorly kept tutorial.

Besides that, I have no way of really debugging your code. The code sample is nice but it is hard to say without a live site.

I also need to mention that the [Contributing Guidelines](https://github.com/imakewebthings/waypoints/blob/master/CONTRIBUTING.md) and Readme note that this is a bug tracker, not a help forum. Stack Overflow, specifically [this tag](http://stackoverflow.com/questions/tagged/jquery-waypoints) are great for asking usage questions and getting answers, assuming you've followed the helpful [guidelines for asking good questions](http://stackoverflow.com/help/how-to-ask).

**Comment by henlnhl** [comment]
Im actually using 1.1.7, my IS shop does a less than stellar job of keeping things up to date. I had been advised by the team that brought Waypoints in that they had exhausted their debugging efforts and they thought this was a potential bug in the library.

**Comment by imakewebthings** [comment]
@henlnhl It's still impossible for me to debug further without seeing the bug in action. If you would like to provide a link, please do that and reopen the ticket.
