### ISSUE TITLE
infinite scroll with infinite loop

### ISSUE THREAD

**Issue by radin-reth** [imakewebthings/waypoints#386]
Dear, @imakewebthings 

Waypoints Infinite is not working properly when It reaches to the end of the page then it looks for data from the first page and continually repeat again and again.

thanks

**Comment by imakewebthings** [comment]
@radin-reth Can you share with me a page where this is happening?

**Comment by radin-reth** [comment]
hi @imakewebthings 
http://iwstaging.yoolk.com/announcements?alias_id=kh54997&color=blue&locale=en&theme=business_pundit

**Comment by imakewebthings** [comment]
@radin-reth Is that page still exhibiting the problem you've described? Because I don't see that happening. Is it browser specific?

**Comment by radin-reth** [comment]
hi @imakewebthings , just to solve the current problem I have just customized some of your code for internal use.

**Comment by CHH** [comment]
@imakewebthings this problem occurs on my current project too, sometimes. I'm working on reproducing it reliably, though.

**Comment by CHH** [comment]
@imakewebthings is there some kind of resolution for this problem?

**Comment by imakewebthings** [comment]
@CHH I couldn't get any further information from @radin-reth and he seems to have solved his issue in some way. If you have the reproduction you were working on nailing down feel free to open another issue.

**Comment by CHH** [comment]
@imakewebthings ok

**Comment by radin-reth** [comment]
Excuse me, guys!
Thanks for involve, Actually, I am working on a private repo of one company that's why I create a new gist about what I have changed @imakewebthings  code in order to solve my problem [waypoints infinite scroll with infinite loop](https://gist.github.com/radin-reth/70ca3a973df95640e53a)

**Comment by JFK1980** [comment]
I'm having this issue also. I have narrowed the problem down to window size. (On a large iMac screen) If I have the window smaller than the initial number of items on the page, then it loads the next (3) pages items just fine, but if the window is taller than the (3) pages' number of items then it loops back to the first page's items and appends them infinitely underneath the items that I expected to load.

Hope that makes sense, kind of hard to explain. Basically, I think it only happens when the window is taller than the number of items available to load.
