### ISSUE TITLE
Don't set height for wrapper if no wrapper needed

### ISSUE THREAD

**Issue by marczking** [imakewebthings/waypoints#392]
I have a `header` which is fixed from the start. When I start scrolling I add `.stuck`

Also I set `wrapper: null`, so no element is wrapped around my existing header.

> The wrapper height is set. This ensures the wrapper is the same height as the element it wraps, even when that element becomes fixed. This prevents the page layout from shifting when it does.

According to the spec my body is getting a `height: 1000px;` set (because no other wrapper is set). Is there a way to just toggle the class without any wrapper stuff happening?

**Comment by imakewebthings** [comment]
@marczking It sounds like what you need is a plain old Waypoint, not the Sticky shortcut. The Sticky shortcut is basically:

- A wrapper around the "real" target.
- A waypoint on that wrapper that toggles a class.
- Height setting of that wrapper to ensure content jumps don't happen.

Since you don't need two of those, you may be able to go with a waypoint on your preexisting wrapper. I'll call it `.header-parent` here:

```js
$('.header-parent').waypoint(function(direction) {
  $('header').toggleClass('stuck', direction === 'down');
});
```

**Comment by marczking** [comment]
thanks! I'll give it a go :smile:
