### ISSUE TITLE
API changes for 4.0.0?

### ISSUE THREAD

**Issue by axe312ger** [imakewebthings/waypoints#440]
Hey there,

about one year ago, we had troubles do a change request for an old project using Waypoints 2 since the documentation was replaced by the one for Waypoints 3.

What about version 4 you just released? Any major API changes? Will the docs for 3 stay online? And if there are no big changes, why pushing a new major version?

Thx for your work, waypoints is great. Just want to know what your intention behind that relese is :)

**Comment by imakewebthings** [comment]
@axe312ger Great question. First, I want to say that I still intend to write a Guide under the guides section for upgrading from 2.x to the current version. You may notice by my GitHub contribution graph that demands on my time have changed in recent months.

The short answer is no, there were no API changes. There were a handful of small API additions noted in the `CHANGELOG.md`, but no breaking API changes. Continue on as before.

The slightly longer answer is **yes**, there is a breaking API change. It's the only reason to bump the major version. But I would also bet money that the change is one that zero people were relying on in production. Here it is:

```js
console.log('1')
$('#thing').waypoint(function() {
  console.log('2')
})
console.log('3')
```

You click on a link to this page with a hash fragment that takes you to the bottom of the page, past where `#thing`'s waypoint would have fired, before this code block has run. When it runs under 3.1.1, you will get the output...

```
1
2
3
```

With 4.0+ you will see...

```
1
3
2
```

The change is: When a waypoint is instantiated, it does a check to see if it should have been triggered already, and if it should have, it triggers its handler. Previously that happened immediately. Now it is pushed to the next requestAnimationFrame.

I was breaking a fundamental rule of async api design, [mixing the possibility of sync and async execution](http://blog.ometer.com/2011/07/24/callbacks-synchronous-and-asynchronous/) of a callback, thus [releasing Zalgo](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony). Fixing this had the effect of clearing up a few outstanding bugs that were stumping me.

Again, I anticipate that nobody was depending on sync execution of the callback in this case, but since **technically maybe** I bumped the major. I'd rather liberally bump the major on the off chance of breaking existing consumer code.
