### ISSUE TITLE
Window Resize doesn't trigger refresh when waypoint has a context other than window

### ISSUE THREAD

**Issue by johngrogg** [imakewebthings/waypoints#442]
This is due to the fact that the resize event only fires for the window element. `Context.prototype.createThrottledResizeHandler` needs to have the 'resize.waypoints' event binding always be bound to the window element, regardless of context.

**Comment by shellscape** [comment]
@imakewebthings ping. please do have a look at this one. we're suffering from the same problem.

**Comment by imakewebthings** [comment]
@johngrogg Agreed this needs to be changed, but not exactly in the way proposed in the PR. Rather than bind create a `windowAdapter` for each context, each with its own `resizeHandler`, we can create one window adapter and throttle a call to `Waypoint.refreshAll()`. I believe Waypoints did this in the 2.x days and I can't for the life of me remember a reason why I would have removed it, except for forgetfulness.

**Comment by imakewebthings** [comment]
Fixed in the 4.0.1 release.
