### ISSUE TITLE
Waypoint not triggering the handler properly when lazy loading images on the page

### ISSUE THREAD

**Issue by gpapin** [imakewebthings/waypoints#444]
I've setup waypoint properly, everything was fine until I added the [lazyloading.js](http://www.appelsiini.net/projects/lazyload) plugin to my page, now the waypoint handler is triggered way before the attached element is shown on the page. 
Any way to make both works ?

**Comment by stehefan** [comment]
This happens, because the images change the height of the container and therefore, the waypoint will get earlier as wanted, because you don't recalculate the waypoints after those images are loaded.

You could set the widths and heights in CSS of the images so that they don't change dimensions after loading. Or you could use another library for lazyloading like [lazysizes](https://github.com/aFarkas/lazysizes), which throws events when finished loading images so that you can listen to them and re-calculate the waypoints.

**Comment by imakewebthings** [comment]
```
$('img.lazy').waypoint(function () {
  var $element = $(this.element)

  this.destroy()
  $element.on('load', function () {
    Waypoint.refreshAll()
    $(this).waypoint({
      // Whatever waypoint stuff you're doing that you haven't shared
    })
  }), 
  $element.attr('src', $element.data('original'))
},
  offset: '100%'
})
```

@gpapin That should do what you want **and** uses Waypoints to do the lazy loading rather than load another plugin.
