### ISSUE TITLE
Trigger Method

### ISSUE THREAD

**Issue by RRorg** [imakewebthings/waypoints#446]
As it says in the title, a method to trigger a waypoint instance manually would be superb.

**Comment by stehefan** [comment]
What exactly do you want to trigger? The Method you're binding to the waypoint? If so, you could just call the method your binding there.

**Comment by RRorg** [comment]
Sure, that works, but it does have a slightly hack-ish feeling to it - and is not the same, since you can't call anonymous functions that way and don't easily have access to the Waypoint instance via `this`.

I feel like providing a clean way to trigger the waypoints would be beneficial for clean, straight-forward code.

**Comment by imakewebthings** [comment]
@RRorg As an industry we've overloaded this word, "clean", to mean anything and everything. Most of us can agree on some things, a lot of us could argue about the details, and none of us would be right or wrong.

On this specific matter it seems we have differing opinions. I don't believe using a Waypoint as a storage tool for methods is wise. For the same reasons that I don't do this:

```js
var el = $('#el')
el.on('click', function () {
  // Let say, a bunch of logic to load a new page from
  // a server and append elements
})

// Somewhere else, another interaction that would load a new page
el.trigger('click')
```

Method invocation in JavaScript is not a hack. Wouldn't you rather...?

```js
var el = $('#el')

function loadNewPage () {
 // Page loading logic
}

el.on('click', function () {
  loadNewPage()
})

// Somewhere else, another interaction that would load a new page
loadNewPage()
```

With Waypoints, I'd suggest, and even recommend in *any* situation, a pattern of handling the waypoints specific stuff (let's be honest here, usually `direction` logic) then calling out to the more generally useful function.

```js
$('.el').waypoint(function (direction) {
  if (direction === 'down') {
    doDownStuff()
  } else {
    doUpStuff()
  }
})

function doDownStuff () {
  ...
}

function doUpStuff () {
  ...
}
```

Hopefully you've closed the tab by now, because here I spill the beans that there already is [a trigger method](https://github.com/imakewebthings/waypoints/blob/0944e1569dd46a05494c3c056e4328884a739a4f/src/waypoint.js#L47-L55). It takes a single array as an argument, and that array is used as the arguments to the handler callback. So: `waypoint.trigger(['down'])`. It does not trigger if the waypoint is disabled. It's also **private** which in the scope of this project only means that it is undocumented, not intended for public use, and could be refactored out of existence at any release.
