### ISSUE TITLE
jquery.waypoints.js not working in webpack 

### ISSUE THREAD

**Issue by alihaddadkar** [imakewebthings/waypoints#559]
Hello.
I have problem with jquery waypoints. When import jquery.waypoints.js in webpack receiving this error.
Console:
`Uncaught TypeError: Cannot read property 'each' of undefined`

How do I fix this?

**Comment by Braunson** [comment]
I'm having a similar issue with using it in Webpack but receiving the error

```
Uncaught TypeError: Cannot read property 'replace' of undefined
```

**Stack:**
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Waypoint.a [as callback] (admin.f450585….js:8572)
    at Waypoint../node_modules/waypoints/lib/jquery.waypoints.js.Waypoint.trigger (admin.f450585….js:47795)
    at Group../node_modules/waypoints/lib/jquery.waypoints.js.Group.flushTriggers (admin.f450585….js:48267)
    at admin.f450585….js:48174
```

**Comment by jimblue** [comment]
Hi @alihaddadkar,

You should try to add the following code in the **plugins** section of your **webpack** configuration

```
plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    })
  ]
```

**Comment by jmbelloteau** [comment]
anyone?

**Comment by alihaddadkar** [comment]
I added this code to js file. solved.
```
window.jQuery = window.$ = require("jquery");
```

**Comment by vnussolution** [comment]
Thanks jimblue!, your solution works for me.

**Comment by houssemFat** [comment]
ThanKs @jimblue , you saved my day !

**Comment by kkerley** [comment]
Can you show/explain exactly where you added that line @alihaddadkar? I'm having this exact same problem in Foundation 6.4 and am having no luck fixing this due to the lack of context.

This is my webpack.config.js file:
```
module.exports = {
  externals: {
    jquery: 'jQuery'
  },
  plugins: [
      new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          'window.jQuery': 'jquery'
      })
  ],
};

window.jQuery = window.$ = require("jquery");
```

I've put the window.jQuery = window.$ = require("jquery"); line in numerous places and it's made no difference after stoping and restarting Gulp each time.

**Comment by alihaddadkar** [comment]
@kkerley 
Where did you put `window.jQuery = window.$ = require("jquery");`?

**Comment by kkerley** [comment]
@alihaddadkar I said explicitly where I put it and even included the entire contents of my webpack.config.js file in my question to you. 

Where does that line need to go in order to remove this error? You said you fixed it by adding that line "to js file." Which JS file? Where in the file? How did you fix this issue?

**Comment by mittererr** [comment]
For me `Encore.autoProvidejQuery()` did it!
